name: Publish

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Docs
      run: yarn docs

    # Deploy to GitHub Pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        branch: gh-pages
