name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22' # Using Node.js 22 as requested
          registry-url: 'https://registry.npmjs.org'

      # Enable and prepare Corepack
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - run: yarn install
      - run: sh script/cibuild.sh

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
