name: Publish to npm and Update Docs

on:
#  push:
#    branches:
#      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish-and-update:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Using Node.js 22 as requested
          registry-url: 'https://registry.npmjs.org'

      # Enable and prepare Corepack
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Generate Docs
        run: yarn docs

      - name: Commit and Push Docs
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update docs [skip ci]" || echo "No changes to commit"
          git push

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
